# Generated by Django 2.2.3 on 2020-03-08 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0013_auto_20190724_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarprofile',
            name='Eindex',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='scholarprofile',
            name='Hmedian',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='scholarprofile',
            name='Oindex',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='scholarprofile',
            name='TNCc',
            field=models.CharField(default='00', max_length=100),
        ),
    ]
